[["地下街食人魔"]]
introduce = """\
深入排水系统和动力系统深处看看所谓的\"地下食人魔是什么东西\"
"""

[["地下街食人魔".checkPoints]]
name = "通过满是刺鼻液体的房间"

[["地下街食人魔".checkPoints]]
name = "探查年久失修的地铁系统"

[["地下街食人魔".checkPoints]]
name = "探查\"地下居民区\""
introduce = """\
地下似乎有一个叫\"原住民保留区\"的区域, 看看那里有没有消息
"""
