["风暴中出击"]
introduce = """\
收集 <风暴中出击> 系列小说
"""

[["风暴中出击".checkPoints]]
name = "风暴中出击: 死亡辉光乐队"
introduce = """\
收集到 <风暴中出击: 死亡辉光乐队>
"""

[["风暴中出击".checkPoints]]
name = "风暴中出击: 冲突世界海盗电台"
introduce = """\
收集到 <风暴中出击: 冲突世界海盗电台> 并交给库莉
"""
