[["水电公司区域".items]]
name = "看起来坚固的酒瓶"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "3"]]

[["水电公司区域".items]]
name = "看起来不坚固的酒瓶 X 3"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "1"]]

[["水电公司区域".items]]
name = "看起来不坚固的酒瓶 X 3"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "1"]]

[["水电公司区域".desserts]]
name = "酒瓶"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "1d4 - 1 (小于1记为1)"]]

[["水电公司区域".desserts]]
name = "酒瓶"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "1d4 - 1 (小于1记为1)"]]

[["水电公司区域".desserts]]
name = "酒瓶"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "1d4 - 1 (小于1记为1)"]]
