[["水电公司区域".items]]
name = "看起来坚固的酒瓶"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "3"]]

[["水电公司区域".items]]
name = "看起来不坚固的酒瓶 X 3"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [["临时武器"], ["不趁手武器"], ["特殊效果", "用数次就会碎掉"], ["剩余使用次数", "1"]]

[["水电公司区域".desserts]]
name = "酒瓶"
introduce = """\
虽然只是一般的酒瓶, 用起来也不顺手, 但是砸在脑袋上还是能要命的.
重击 15 ~ 20, 触发重击会直接碎掉.
伤害不论体型, 一般情况下伤害是 1d2, 最后一次攻击或重击时候附带 1d3 挥砍伤害.
"""
tags = [
  [
    "临时武器",
  ],
  [
    "不趁手武器",
  ],
  [
    "特殊效果",
    "用数次就会碎掉",
  ],
  [
    "剩余使用次数",
    "1d4 - 1 (小于1记为1)",
  ],
]

[["莫纳卡和布罗托夫斯基关于泵站的交谈".items]]
name = "那个泵"
introduce = """\
莫纳卡: "那个泵又坏了?"
布罗托夫斯基: "不知道涡轮又绞到是什么东西, 明明是给水的."
莫纳卡: "你的意思是给水系统被污染了? 安全事故?"
布罗托夫斯基: "不是生活用水, 而且是旁路."
莫纳卡: "污染源呢? 定位到了吗?"
布罗托夫斯基: "在排查, 但是是老线路了, 通过地方涉及到保留地."
莫纳卡: "保留地? 水电公司啥时候还给他们也供水了?"
布罗托夫斯基: "历史产物了, 上面的意思也是, 如果有必要就关停."
"""
tags = [["交谈"]]

[["莫纳卡和布罗托夫斯基关于泵站的交谈".desserts]]
name = "抱怨"
introduce = """\
布罗托夫斯基: "我真不知道, 诶, 那群动力车间的废物是干什么的, 一个泵三天两头坏."
莫纳卡: "别这样, 想开点至少丘陵已经过去了, 我想要不了多久我们就可以还清贷款了."
"""
tags = [["交谈"]]

[["给排水系统巡检员与管阀厂工人的闲聊".items]]
name = "地下迷宫"
introduce = """\
图格里芬: "我的意思是城区这么多人的吃喝拉撒, 那得多大的管道?"
乌庞博: "下面可比上面大多了, 我在干巡检员已经快 20 个年头了, 但是出了路线一点都不敢."
宝登: "下面会见到他们吗? 我是说保留地的人?"
迈尔: "难, 我们只是沿着管道每天完成巡检任务罢了, 他们可是生活在那里."
"""
tags = [["交谈"]]

[["给排水系统巡检员与管阀厂工人的闲聊".desserts]]
name = "地下迷宫"
introduce = """\
图格里芬: "下面我可不敢去."
乌庞博: "瞧你身上那些块, 怕啥, 找时间我们下去溜达溜达."
"""
tags = [["交谈"]]

[["红色封面的书".items]]
name = "风暴中出击: 死亡辉光乐队"
introduce = """\
作者: 海因莱茵

这是一本传记性质的小说, 记录了被称为"死亡辉光乐队"的某个红极一时的地下实验摇滚乐队的经历.
这支乐队活跃于上世纪 80 年代末到 90 年代早期, 是当时流行的海盗电台文化产物.
改组后的光明矢整合了大量前中央警卫局成员协同傀儡政府对各个下层城市展开文化清洗,
将此前的无数私人电台尽数捣毁,
对文化未经授权的载体, 如磁带黑胶录像带印刷品进行了大大小小无数场焚烧,
最大的一场大火烧了两个多星期.

但这并没有难倒秘密结社的成员, 他们利用飞艇冒死停留在雷暴云层缝隙之间,
利用大功率射频指向天线将他们的节目广播, 这些电台被称为地下电台或海盗电台.
由于播出时间不可控, 海盗电台需要大量可以提前录制或可以简单的再创作的节目,
他们有时将大量的政治宣传歌曲remix成戏谑的搞笑流行曲目,
这被称为红色波普艺术, 不过这对电台主播的合成器效果器使用功底要求过高,
所以大部分电台和其他地下音频内容生产组织合作.

死亡辉光乐队就是在这一时期一炮走红的, 作为红色原子朋克摇滚浪潮的领军乐队,
他们喜欢模仿被禁止的音乐做词风格套上实验室风格的死亡摇滚,
彻彻底底的解放人们被束缚的内心. 在表演形式上他们也极尽奔放,
开着简陋的气球飞艇在夜晚靠近移动城市的露天广场展开赤旗带着舞台一起落下引吭高歌,
然后混入人群, 只留下被击毁飞艇和一地的录音带.

但是在一场演出前, 他们的信息被泄露, 飞艇将接近城市就被击毁,
他们干脆直接在燃烧下落的飞艇甲板上演奏, 直到化为废墟.
为了纪念他们, 每到他们的死亡纪念日, 无数海盗电台就会播放起他们的曲目.
"""
tags = [["书籍"]]

[["红色封面的书".items]]
name = "风暴中出击: 冲突世界海盗电台"
introduce = """\
作者: 海因莱茵

这是一本传记性质的小说, 记录了被称为"冲突世界"的某个红极一时的海盗电台.
冲突世界本来是个名不见经传的双人私人小电台,
虽然凭借主持人兼唱片骑士博克熟练的技巧和策划沃尔出色的品味在业内小有名气,
但和那些渠道丰富人员充足的大电台比,
这个一半音乐一半电杂音白噪的电台可以开下来都是奇迹了.
而更加雪上加霜的是清洗运动时警卫队干脆连着设备一起砸了.

但有一天, 一个瞎了一只眼瘸了一条腿的胖矮人黑船长带着一个硬壳飞艇找过来,
三个人一拍即合, 黑船长找波利兄弟会的朋友搞来射频天线和大功率无线电,
博客在家里翻出自己的碟机, 合成器和效果器, 沃尔找朋友搞来各种各样的碟片.
于是冲突世界海盗电台正式开张.

他们率先开创了海盗电台卖碟片的商业方式, 趁着夜色给大街小巷贴上红黑相间的拼接海报,
砍掉主持人的“废话”专心播音乐. 甚至有时还会"绑架"当红乐队,
就是请他们带上眼罩到"演播室"高歌一曲.
于是大获成功开创了海盗电台这一前无古人的电台模式, 成为一代传奇.
"""
tags = [["书籍"]]

[["红色封面的书".desserts]]
name = "隐秘的城市"
introduce = """\
作者: 罗威尔阿克-罗塔伊

这本小说分了22个独立的章节来讲述一个位于曾经的国度"灰港"中的一座隐秘的城市.
由在成为大发明家之前四处旅行的波罗塔尔向报社编辑口述并编纂成集.

然而, 书中所描述的并不是实际存在的城市,
而是一种寓言或象征, 探讨了记忆、期望、痛苦、快乐等主题.
小说的城市虽然在形式上有所不同, 但却逐渐揭示出一种可能的解读,
即所有的城市实际上都是同一座城市的不同面貌.

这座城市可以看作是一种想象的空间, 或者是人类经验、欲望和恐惧的象征.
其中的城市名字都是以女性名字命名, 象征着这些城市可能存在的多种意象和情感.
这种城市的描述并非实际的地理或建筑描绘,
而是一种情感和意识状态的映射, 描绘了我们对于城市、生活和人性的深层理解.
"""
tags = [["书籍"]]
